=== uwlib-cams/map_storage/get_prop_sets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://uwlib-cams.github.io/map_storage/"
    xmlns="https://uwlib-cams.github.io/map_storage/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">

    <!-- why are these here again? -->
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <!-- [?] xs:import below results in error -->
    <xs:import namespace="http://www.w3.org/2001/XMLSchema"
        schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>

    <xs:element name="get_prop_sets" type="get_prop_sets_type"/>

    <xs:complexType name="get_prop_sets_type">
        <xs:sequence>
            <xs:element name="get_set" type="get_set_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="get_set_type">
        <xs:sequence>
            <xs:element name="set_name" type="set_name_type"/>
            <xs:element name="set_source" type="set_source_type"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="set_name_type">
        <xs:restriction base="xs:string">
            <!-- same as map_storage.xsd > mapid_pro_set_attr_type -->
            <!-- [?] is it possible to put enumeration lists that will need updating, like this one, in an external doc and import here as vars, etc.? 
                See map_storage #5 -->
            <xs:enumeration value="rdacWork"/>
            <xs:enumeration value="rdacExpression"/>
            <xs:enumeration value="rdacManifestation"/>
            <!-- Not yet in test storage instance
            <xs:enumeration value="rdacIPropSet"/>
            <xs:enumeration value="rdacAPropSet"/>
            <xs:enumeration value=""/>
            -->
            <xs:enumeration value="dcTerms"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="set_source_type">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>

</xs:schema>

=== uwlib-cams/map_storage/xml/get_prop_sets.xml
<?xml version="1.0" encoding="UTF-8"?>
<get_prop_sets xmlns="https://uwlib-cams.github.io/map_storage/xsd/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://uwlib-cams.github.io/map_storage/xsd/ 
    https://uwlib-cams.github.io/map_storage/xsd/get_prop_sets.xsd">
    
    <!-- [!] CAUTION / DON'T OVERWRITE RDA prop_set > implementation_sets [!] pending map_storage #10 -->
    <get_set>
        <set_name>rdaw_p10k</set_name>
        <set_domain>rdaWork</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/w.xml</set_source>
    </get_set>
    <get_set>
        <set_name>rdae_p20k</set_name>
        <set_domain>rdaExpression</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/e.xml</set_source>
    </get_set>
    <get_set>
        <set_name>rdam_p30k</set_name>
        <set_domain>rdaManifestation</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/m.xml</set_source>
    </get_set>
    <get_set>
        <set_name>rdai_p40k</set_name>
        <set_domain>rdaItem</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/i.xml</set_source>
    </get_set>
    <get_set>
        <set_name>rdaa_p50k</set_name>
        <set_domain>rdaAgent</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/a.xml</set_source>
    </get_set>
    <get_set>
        <set_name>rdan_p80k</set_name>
        <set_domain>rdaNomen</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/n.xml</set_source>
    </get_set>
    <get_set>
        <set_name>rdap_p70k</set_name>
        <set_domain>rdaPlace</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/p.xml</set_source>
    </get_set>
    <get_set>
        <set_name>rdat_p70k</set_name>
        <set_domain>rdaTimespan</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/t.xml</set_source>
    </get_set>
    <get_set>
        <set_name>rdax_p00k</set_name>
        <set_domain>rdaEntity</set_domain>
        <set_source>https://github.com/RDARegistry/RDA-Vocabularies/raw/master/xml/Elements/x.xml</set_source>
    </get_set>
    <!-- [!] CAUTION: Don't overwrite RDA prop_set > implementation_sets pending resolution of #10 -->

    <get_set>
        <set_name>uwRdaExtension</set_name>
        <!-- [!] CAUTION: RDF/XML URL will change for updates to dataset -->
        <set_source>https://www.lib.washington.edu/static/public/cams/data/localResources/rdaApplicationProfileExtension-1-0-1.rdf</set_source>
    </get_set>
    
    <!-- NOT USING DC TERMS, PROV AT PRESENT -->
    <get_set>
        <set_name>dcterms</set_name>
        <set_source>https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.rdf</set_source>
    </get_set>
    <get_set>
        <set_name>prov</set_name>
        <set_source>http://www.w3.org/ns/prov.owl</set_source>
    </get_set>
    
</get_prop_sets>
