=== uwlib-cams/map_storage/xsd/prop_set.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- are both targetNamespace and xmlns attrs needed? -->
<xs:schema targetNamespace="https://uwlib-cams.github.io/map_storage/xsd/"
    xmlns="https://uwlib-cams.github.io/map_storage/xsd/" 
    xmlns:uwsinopia="https://uwlib-cams.github.io/sinopia_maps/xsd/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">

    <!-- ***** IMPORT/INCLUDE ***** -->
    
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XMLSchema"
        schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>
    <xs:import namespace="https://uwlib-cams.github.io/sinopia_maps/xsd/"
        schemaLocation="https://uwlib-cams.github.io/sinopia_maps/xsd/uwsinopia.xsd"/>
    
    <!--  ***** REUSE THESE TYPES ***** -->
    
    <xs:simpleType name="prop_set_label_type">
        <xs:annotation>
            <xs:documentation>For RDA property sets:</xs:documentation>
            <xs:documentation>These options correspond to documents published at the RDA Registry detailing RDA/RDF properties for use with a given domain.</xs:documentation>
            <xs:documentation>Most property-set labels will be self-explanatory, but note that...</xs:documentation>
            <xs:documentation>The 'rdax_p00k' property set includes properties for use with the class 'RDA Entity'.</xs:documentation>
            <xs:documentation>For other property sets:</xs:documentation>
            <xs:documentation>The 'dcterms' property set includes the Dublin Core Terms.</xs:documentation>
        </xs:annotation>
        <!-- (MAP ID component) -->
        <xs:restriction base="xs:string">
            <xs:enumeration value="rdaw_p10k"/>
            <xs:enumeration value="rdae_p20k"/>
            <xs:enumeration value="rdam_p30k"/>
            <xs:enumeration value="rdai_p40k"/>
            <xs:enumeration value="rdaa_p50k"/>
            <xs:enumeration value="rdan_p80k"/>
            <xs:enumeration value="rdap_p70k"/>
            <xs:enumeration value="rdat_p70k"/>
            <xs:enumeration value="rdax_p00k"/>
            <!-- RDA/ONIX Framework element set not yet added  -->
            <!-- RDA unconstrained not yet added -->
            <!-- RDA metadata element properties (Deprecated) will not be added -->
            <xs:enumeration value="dcterms"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="resource_label_type">
        <xs:restriction base="xs:string">
            <!-- (MAP ID component) -->
            <xs:enumeration value="rdaWork"/>
            <xs:enumeration value="rdaAgent"/>
            <xs:enumeration value="rdaItem"/>
            <xs:enumeration value="rdaPerson"/>
            <xs:enumeration value="rdaCorporateBody"/>
            <xs:enumeration value="rdaExpression"/>
            <xs:enumeration value="rdaManifestation"/>
            <xs:enumeration value="rdaFamily"/>
            <xs:enumeration value="rdaPlace"/>
            <xs:enumeration value="rdaTimespan"/>
            <xs:enumeration value="rdaCollectiveAgent"/>
            <xs:enumeration value="rdaNomen"/>
            <xs:enumeration value="rdaEntity"/>
            <!-- enumeration below for testing to do delete later -->
            <xs:enumeration value="testMultiplePropSets"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="lang_string_type">
        <!-- Use values from https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry  -->
        <!-- to do need default "en" -->
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
                <!-- to do / wishlist / question: possible to add enumerations here?? -->
                <!-- en -->
                <!-- zxx -->
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="localid_attr">
        <xs:restriction base="xs:string">
            <!-- Possible to an XSD mechanism to prevent duplicate values? -->
            <xs:pattern value="\S+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="iri_type">
        <xs:attribute name="iri">
            <xs:simpleType>
                <xs:restriction base="xs:anyURI">
                    <!-- IRI validation pattern -->
                    <xs:pattern value="https?:\/\/\S*"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <!-- ********* SCHEMA ********* -->

    <!-- **** prop_set **** -->
    <xs:element name="prop_set" type="prop_set_type"/>
    
    <xs:complexType name="prop_set_type">
        <xs:sequence>
            <xs:element name="prop_set_label" type="prop_set_label_type" minOccurs="1"
            maxOccurs="1"/>
            <xs:element name="prop" type="prop_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- *** prop *** -->
    <xs:complexType name="prop_type">
        <xs:sequence>
            <xs:element name="prop_iri" type="iri_type" minOccurs="1" maxOccurs="1"/>
            <xs:element name="prop_label" type="lang_string_type" minOccurs="1"
                maxOccurs="unbounded"/>
            <xs:element name="prop_domain" type="iri_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prop_domain_includes" type="iri_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prop_range" type="iri_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prop_range_includes" type="iri_type" minOccurs="0" maxOccurs="unbounded"/>
            <!-- CONSIDER creating additional elements so that URLs can be stored for 1) output as ref links to appear in Sinopia UI and
                2) output as ref links with descriptive text to appear in HTML -->
            <xs:element name="prop_related_url" type="url_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="sinopia" type="uwsinopia:sinopia_type" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="localid_prop" type="localid_attr" use="required"/>
    </xs:complexType>

    <!-- BMR TO DO [!] This element needs work; attributes need better constraints -->
    <xs:complexType name="url_type">
        <xs:simpleContent>
            <!-- Need to improve constraints on URL values here; xs:anyURI alone not effective -->
            <xs:extension base="xs:anyURI">
                <xs:attribute name="url"/>
                <!-- Use values to differentiate 1) output as ref links to appear in Sinopia UI vs. 2) output as ref links with descriptive text to appear in HTML -->
                <!-- Need to enumerate link_category, one category should be remark URL -->
                <xs:attribute name="link_category"/>
                <!-- Maybe store link text as text child, not in @ -->
                <xs:attribute name="link_text"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>    

</xs:schema>

=== uwlib-cams/map_storage/prop_set_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<prop_set xmlns="https://uwlib-cams.github.io/map_storage/xsd/"
          xmlns:dcam="http://purl.org/dc/dcam/"
          xmlns:owl="http://www.w3.org/2002/07/owl#"
          xmlns:prov="http://www.w3.org/ns/prov#"
          xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
          xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
          xmlns:reg="http://metadataregistry.org/uri/profile/regap/"
          xmlns:uwmaps="https://uwlib-cams.github.io/map_storage/xsd/"
          xmlns:uwsinopia="https://uwlib-cams.github.io/sinopia_maps/xsd/"
          xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://uwlib-cams.github.io/map_storage/xsd/ https://uwlib-cams.github.io/map_storage/xsd/prop_set.xsd">
   <prop_set_label>rdaa_p50k</prop_set_label>
   <uwmaps:prop localid_prop="uwmaps_rdaa_p50k_aP50157">
      <prop_iri iri="http://rdaregistry.info/Elements/a/P50157"/>
      <prop_label xml:lang="en">is abridger agent of</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10002"/>
   </uwmaps:prop>
   <uwmaps:prop localid_prop="uwmaps_rdaa_p50k_aP50766">
      <prop_iri iri="http://rdaregistry.info/Elements/a/P50766"/>
      <prop_label xml:lang="en">is abridger collective agent of</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10011"/>
   </uwmaps:prop>
   <uwmaps:prop localid_prop="uwmaps_rdaa_p50k_aP50917">
      <prop_iri iri="http://rdaregistry.info/Elements/a/P50917"/>
      <prop_label xml:lang="en">is abridger corporate body of</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10005"/>
   </uwmaps:prop>
   <uwmaps:prop localid_prop="uwmaps_rdaa_p50k_aP51068">
      <prop_iri iri="http://rdaregistry.info/Elements/a/P51068"/>
      <prop_label xml:lang="en">is abridger family of</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10008"/>
   </uwmaps:prop>
</prop_set>

=== uwlib-cams/map_storage/prop_set_uwRdaExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<prop_set xmlns="https://uwlib-cams.github.io/map_storage/xsd/"
          xmlns:dcam="http://purl.org/dc/dcam/"
          xmlns:owl="http://www.w3.org/2002/07/owl#"
          xmlns:prov="http://www.w3.org/ns/prov#"
          xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
          xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
          xmlns:reg="http://metadataregistry.org/uri/profile/regap/"
          xmlns:uwmaps="https://uwlib-cams.github.io/map_storage/xsd/"
          xmlns:uwsinopia="https://uwlib-cams.github.io/sinopia_maps/xsd/"
          xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://uwlib-cams.github.io/map_storage/xsd/ https://uwlib-cams.github.io/map_storage/xsd/prop_set.xsd">
   <prop_set_label>uwRdaExtension</prop_set_label>
   <prop localid_prop="uwmaps_uwRdaExtension_hasCreatorCharacteristic_prop_d13e130">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasCreatorCharacteristic"/>
      <prop_label xml:lang="en">Has Creator Characteristic</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10001"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasContributorAgent_prop_d13e164">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasContributorAgent"/>
      <prop_label xml:lang="en">Has Contributor Agent</prop_label>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasUniversityOfWashingtonNote_prop_d13e193">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasUniversityOfWashingtonNote"/>
      <prop_label xml:lang="en">Has University Of Washington Note.</prop_label>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_heldBy_prop_d13e227">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#heldBy"/>
      <prop_label xml:lang="en">Held By</prop_label>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasLcClassificationPartA_prop_d13e255">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasLcClassificationPartA"/>
      <prop_label xml:lang="en">Has LC Classification Part A</prop_label>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasLcClassificationPartB_prop_d13e289">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasLcClassificationPartB"/>
      <prop_label xml:lang="en">Has LC Classification Part B</prop_label>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasNlmClassificationPartA_prop_d13e323">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasNlmClassificationPartA"/>
      <prop_label xml:lang="en">Has NLM Classification Part A</prop_label>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasNlmClassificationPartB_prop_d13e357">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasNlmClassificationPartB"/>
      <prop_label xml:lang="en">Has NLM Classification Part B</prop_label>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasLcGeographicClassification_prop_d13e391">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasLcGeographicClassification"/>
      <prop_label xml:lang="en">Has LC Geographic Classification</prop_label>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasSuDocClassificationNumber_prop_d13e425">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasSuDocClassificationNumber"/>
      <prop_label xml:lang="en">Has SuDoc Classification Number</prop_label>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasPhysicalLocation_prop_d13e459">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasPhysicalLocation"/>
      <prop_label xml:lang="en">Has Physical Location</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10003"/>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasPhysicalSubLocation_prop_d13e499">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasPhysicalSubLocation"/>
      <prop_label xml:lang="en">Has Physical Sub-Location</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10003"/>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasBarcode_prop_d13e538">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasBarcode"/>
      <prop_label xml:lang="en">Has Barcode</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10003"/>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
   <prop localid_prop="uwmaps_uwRdaExtension_hasCallNumber_prop_d13e577">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasCallNumber"/>
      <prop_label xml:lang="en">Has Call Number</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10003"/>
      <prop_range iri="http://www.w3.org/2000/01/rdf-schema#Literal"/>
   </prop>
</prop_set>

=== uwlib-cams/map_storage/prop_set_rdaExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<prop_set xmlns="https://uwlib-cams.github.io/map_storage/xsd/"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
          xmlns:reg="http://metadataregistry.org/uri/profile/regap/"
          xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
          xmlns:uwmaps="https://uwlib-cams.github.io/map_storage/xsd/"
          xmlns:uwsinopia="https://uwlib-cams.github.io/sinopia_maps/xsd/"
          xmlns:dcam="http://purl.org/dc/dcam/"
          xmlns:prov="http://www.w3.org/ns/prov#"
          xmlns:owl="http://www.w3.org/2002/07/owl#"
          xsi:schemaLocation="https://uwlib-cams.github.io/map_storage/xsd/ https://uwlib-cams.github.io/map_storage/xsd/prop_set.xsd">
   <prop_set_label>rdaExtension</prop_set_label>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e130">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasCreatorCharacteristic"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e164">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasContributorAgent"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e193">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasUniversityOfWashingtonNote"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e227">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#heldBy"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e255">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasLcClassificationPartA"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e289">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasLcClassificationPartB"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e323">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasNlmClassificationPartA"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e357">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasNlmClassificationPartB"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e391">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasLcGeographicClassification"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e425">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasSuDocClassificationNumber"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e459">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasPhysicalLocation"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e499">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasPhysicalSubLocation"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e538">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasBarcode"/>
      <prop_label xml:lang="en"/>
   </prop>
   <prop localid_prop="uwmaps_rdaExtension_prop_d12e577">
      <prop_iri iri="https://doi.org/10.6069/uwlib.55.d.4#hasCallNumber"/>
      <prop_label xml:lang="en"/>
   </prop>
</prop_set>

=== uwlib-cams/map_storage/prop_set_rdax_p00k.xml
<?xml version="1.0" encoding="UTF-8"?>
<prop_set xmlns="https://uwlib-cams.github.io/map_storage/xsd/"
          xmlns:dcam="http://purl.org/dc/dcam/"
          xmlns:owl="http://www.w3.org/2002/07/owl#"
          xmlns:prov="http://www.w3.org/ns/prov#"
          xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
          xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
          xmlns:reg="http://metadataregistry.org/uri/profile/regap/"
          xmlns:uwmaps="https://uwlib-cams.github.io/map_storage/xsd/"
          xmlns:uwsinopia="https://uwlib-cams.github.io/sinopia_maps/xsd/"
          xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://uwlib-cams.github.io/map_storage/xsd/ https://uwlib-cams.github.io/map_storage/xsd/prop_set.xsd">
   <prop_set_label>rdax_p00k</prop_set_label>
   <prop localid_prop="uwmaps_rdax_p00kx_P00016_prop_d12e49">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00016"/>
      <prop_label xml:lang="en">has access point for RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00017_prop_d12e258">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00017"/>
      <prop_label xml:lang="en">has appellation of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00020_prop_d12e468">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00020"/>
      <prop_label xml:lang="en">has authorized access point for RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00029_prop_d12e675">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00029"/>
      <prop_label xml:lang="en">has category of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00018_prop_d12e906">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00018"/>
      <prop_label xml:lang="en">has identifier for RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00019_prop_d12e1110">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00019"/>
      <prop_label xml:lang="en">has name of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00015_prop_d12e1321">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00015"/>
      <prop_label xml:lang="en">has note on RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00021_prop_d12e1524">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00021"/>
      <prop_label xml:lang="en">has preferred name of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00024_prop_d12e1744">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00024"/>
      <prop_label xml:lang="en">is RDA entity critiqued by</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00025_prop_d12e1939">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00025"/>
      <prop_label xml:lang="en">is RDA entity described by</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00026_prop_d12e2137">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00026"/>
      <prop_label xml:lang="en">is RDA entity evaluated by</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00027_prop_d12e2336">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00027"/>
      <prop_label xml:lang="en">is RDA entity reviewed by</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00006_prop_d12e2531">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00006"/>
      <prop_label xml:lang="en">has related agent of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00012_prop_d12e2812">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00012"/>
      <prop_label xml:lang="en">has related collective agent of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00009_prop_d12e3092">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00009"/>
      <prop_label xml:lang="en">has related corporate body of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00028_prop_d12e3379">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00028"/>
      <prop_label xml:lang="en">has related entity of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00003_prop_d12e3584">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00003"/>
      <prop_label xml:lang="en">has related expression of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00008_prop_d12e3865">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00008"/>
      <prop_label xml:lang="en">has related family of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00005_prop_d12e4152">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00005"/>
      <prop_label xml:lang="en">has related item of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00004_prop_d12e4434">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00004"/>
      <prop_label xml:lang="en">has related manifestation of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00013_prop_d12e4715">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00013"/>
      <prop_label xml:lang="en">has related nomen of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00007_prop_d12e4993">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00007"/>
      <prop_label xml:lang="en">has related person of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00010_prop_d12e5281">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00010"/>
      <prop_label xml:lang="en">has related place of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00001_prop_d12e5557">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00001"/>
      <prop_label xml:lang="en">has related RDA entity of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00011_prop_d12e5853">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00011"/>
      <prop_label xml:lang="en">has related timespan of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00002_prop_d12e6130">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00002"/>
      <prop_label xml:lang="en">has related work of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00014_prop_d12e6413">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00014"/>
      <prop_label xml:lang="en">is subject RDA entity of</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00022_prop_d12e6623">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00022"/>
      <prop_label xml:lang="en">has variant access point for RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00023_prop_d12e6831">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00023"/>
      <prop_label xml:lang="en">has variant name of RDA entity</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
   <prop localid_prop="uwmaps_rdax_p00kx_P00030_prop_d12e7057">
      <prop_iri iri="http://rdaregistry.info/Elements/x/P00030"/>
      <prop_label xml:lang="en">is RDA entity described with metadata by</prop_label>
      <prop_domain iri="http://rdaregistry.info/Elements/c/C10013"/>
   </prop>
</prop_set>
